apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: custom-nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Skalador/ArgoCD-Demo.git'
    path: dev
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: custom-argo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - CreateNamespace=true
