apiVersion: v1
kind: Service
metadata:
  name: my-nginx-service
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
    nodePort: 31234
